
version: '3.8'
services:
  meilisearch:
    image: getmeili/meilisearch:v1.4
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/data.ms
    environment:
      MEILI_MASTER_KEY: 'masterKey'
volumes:
  meili_data:
